### ISSUE TITLE
Accessing the titlecased text

### ISSUE THREAD

**Issue by dogweather** [peti/titlecase#1]
Hi,

I'm a little confused because Titlecase's signature isn't `:: Text -> Text`. I find that in order to actually get the titlecased result, I must use the internal accesor `unTitlecase`. I find that name confusing, actually, because that does return the titlecased version, not some "unTitlecased" one.

I don't actually see the need, offhand, for the `Titlecase` type. 

Am I missing something?

**Comment by peti** [comment]
The name `unTitlecase` signifies the fact that the function "undoes" the `Titlecase` constructor. Whether one likes that name or not is subjective. I believe it's common practice to name that kind of function in this way and I've certainly seen that same scheme used in other libraries.

**Comment by dogweather** [comment]
Ok, makes sense. What about its placement in `Internal`? I feel like I'm doing something wrong:

```haskell
import          Data.Text.Titlecase             (titlecase)
import          Data.Text.Titlecase.Internal    (unTitlecase)


titleize :: Text -> Text
titleize = unTitlecase . titlecase
```

I.e., would this be better off in `Titlecase` because it's intended to be part of the public API?

**Comment by peti** [comment]
You'll find a new version at http://hackage.haskell.org/package/titlecase-1 that has a much simpler API now, i.e. it's based on `String` and the `Titlecase` type no longer exists.
